### ISSUE TITLE
⌛️ Scheduling and backfill enhancements

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2042]
### Issue description

This issue attempts to consolidate a number of issues related to Scheduling and Backfills.  

---

### Problems

Backfills have evolved into a very important feature for Kestra users. They are now using backfills to trigger mission-critical workflows at scale. To accommodate those new needs, the backfilling feature needs to change. Currently, backfills suffer from several **problems**:
1. They are defined via **code**. The requirement to change code only to trigger backfills causes issues as it unnecessarily increments the Revision and wreaks havoc in the Terraform state when workflow code is managed using Infrastructure as Code.
2. They allow specifying the `start` date but don't allow specifying the `end` date. Our users would like to **trigger backfills for a given time range** between the **start AND end date**. A common use case is coming back to work after the weekend only to realize that Saturday's pipeline failed and data for that specific daily schedule is missing. Being able to set both start and end dates will be able to accommodate that need. See the issue for more details https://github.com/kestra-io/kestra/issues/1768 -- this issue has been closed as we now only want to support the end date from the UI/API and not via code https://github.com/kestra-io/kestra/issues/1762.
3. They can only run **sequentially**, while some users would like to execute hundreds of backfill Executions within a given time range — all of which should run concurrently as they don't depend on each other: https://github.com/kestra-io/kestra/issues/2041 

**Related problem:** 
Currently, all Scheduled executions per trigger ID run sequentially. This means that the next scheduled run will only be executed after the previous scheduled run is finished. This is sometimes not desirable. We would like to add a boolean flag, potentially named `allowConcurrent`, allowing multiple concurrent executions per Scheduled trigger ID: https://github.com/kestra-io/kestra/issues/311. The only blocker for that issue is that it may lead to side effects with backfills. Technical implementation must be validated to allow both concurrent scheduled Executions per trigger ID, as well as concurrent backfills per trigger ID.

### Required changes

The definition of backfills via code must be deprecated. The `backfill` property on the Schedule trigger should raise a deprecation warning. 

The UI must provide an option to backfill Executions:
- for a given `flow ID` and `trigger ID` (_Schedule-type trigger only_)
- for a given `start` and `end` date
- `allowConcurrent` boolean flag to indicate whether the backfill Executions should run sequentially or concurrently
- optionally, allowing to overwrite the `input` values for a given backfill Execution -- the `inputs` are optional property of a Schedule trigger, and it should be possible to trigger a backfill run with a custom input value
- optionally, allow setting custom execution `labels`.

It's likely that we may want to create a **dedicated Backfills page** (e.g. under the Administration section below Triggers) that will provide a dropdown to select:
- a specific namespace, 
- flow ID from that namespace 
- a specific Schedule-type trigger ID from that selected flow

Then, once these fields are configured to **select the relevant Schedule trigger**, the user may leverage a date picker to select the start and end date. Apart from that, there might be a **boolean flag** (set to False by default) allowing users to choose to trigger those backfills **concurrently**. Lastly, users should be able to modify inputs for a given backfill, similarly to how this is possible for ad-hoc Executions from the UI:

![image](https://github.com/kestra-io/kestra/assets/86264395/41812479-4d91-4b26-93f1-681c1d44936e)

Note that a dedicated Backfills page is just an idea. An alternative option would be adding a **Backfill action menu on the Flow page**. The potential complexity of that approach would be making this field dynamic: the Backfills should only be possible if there is at least one Schedule trigger attached to a flow. Additionally, if the user has multiple Schedule-type triggers attached to a Flow, the user would need to select for which trigger ID it should trigger the Backfills. Only then it's possible to configure further details for backfill: `start` date, `end` date, `allowConcurrent` boolean flag, and `inputs` (listed as the usual input fields when creating an Execution). Such a Backfill menu could look similar to the regular "New Execution" menu with the distinction that it would require selecting the trigger ID, start date, end date and the  `allowConcurrent` flag/checkbox. 

### Extra notes for the implementation

Backfills allow the creation of **additional** Executions without affecting the regular schedule interval.

Scheduled executions should be unaffected by Backfills. The regular schedule should continue running according to the usual interval (set using `cron` or `interval`) unless the schedule is disabled. 

---

## Scheduling
 
Apart from backfills, some additional scheduling enhancements have been requested. Backfills currently have the priority, but these are also planned for later this year:
1. There should be a way to allow scheduling some flow for a specific future date without having to define an interval. The goal is to allow to schedule a flow for a list of specific dates: https://github.com/kestra-io/kestra/issues/877 -- this is important for automation and BPM use cases. Example: an employee-onboarding workflow that must be scheduled in advance for the employee's first date.
2. Allow disabling schedule after a failed execution: https://github.com/kestra-io/kestra/issues/1951 to stop consequent executions after a failure. The user's rationale behind this use case is that if you know a given workflow is currently broken (potentially due to issues outside of your control that need to be validated), the orchestrator shouldn't naively schedule the next runs until the broken workflow has been fixed. 
```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/1768
- [ ] https://github.com/kestra-io/kestra/issues/2041
- [ ] https://github.com/kestra-io/kestra/issues/311
- [ ] https://github.com/kestra-io/kestra/issues/877
- [ ] https://github.com/kestra-io/kestra/issues/1951
- [ ] https://github.com/kestra-io/kestra/issues/2219
- [ ] https://github.com/kestra-io/docs/issues/575
- [ ] https://github.com/kestra-io/kestra-ee/issues/611
```

**Comment by anna-geller** [comment]
temporary workaround until end date is added: https://demo.kestra.io/ui/blueprints/community/127

**Comment by anna-geller** [comment]
Small mockup for discussion

![image](https://github.com/kestra-io/kestra/assets/86264395/9ee38461-74ea-4712-aba5-90a73295b1fa)

**Comment by anna-geller** [comment]
Validate from a technical perspective whether we want to support overriding `input` values for backfill run + whether it's feasible.

- allowConcurrent is a boolean, specifying how many concurrent executions are allowed and will be handled as a concurrency limit flow-level feature

**Comment by anna-geller** [comment]
instead of Configure Backfill, use "Backfill Executions"
