### ISSUE TITLE
🎧 Listeners deprecation

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2043]
This issue aims to share the current status of the work related to the listener's deprecation.

The future deprecation warning has already been implemented: https://github.com/kestra-io/kestra/pull/2020. The actual removal will happen in v 0.14.0 or later.   

The remaining issues are listed in the task list.

## Why do we deprecate listeners

1. They require extra workarounds in the codebase
2. They are redundant as a concept -- there is nothing in listeners that you couldn't do with Flow triggers, with the only difference being that listeners are defined inline within the same flow and are more tightly coupled with the flow (e.g., in contrast, Flow trigger can simultaneously listen to the condition of multiple flows that satisfy specific criteria).
3. Extra concept that users need to learn (even though they don't have to if they already know Flow triggers).
4. It's difficult to explain as a concept -- listeners can launch tasks _outside_ of the flow, i.e., tasks that will not be considered part of the flow but they are defined _within_ the flow. Additionally, the results of listeners will not change the execution status of the flow, so having them defined within the flow causes confusion. 
5. Currently, listeners are mainly used to send failure (or success) notifications, and Kestra already has two concepts for that: `triggers` and `errors` tasks. Having **three** choices for such a standard use case leads to unnecessary questions: "Which one is recommended? which of these 3 options should I use to send failure notifications?"

```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/2024
- [ ] https://github.com/kestra-io/kestra/issues/2025
- [ ] https://github.com/kestra-io/docs/issues/479
```
