### ISSUE TITLE
✨ Subflow logs & topology enhancements

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2044]
## Topology

In 0.11.0, the topology view has been redesigned, allowing users to expand and collapse various groups of tasks, including parallel/sequential groups and more. In 0.12.0, we want to extend that functionality to subflows to allow expanding a subflow from the parent flow to see its child tasks. 

Video showing WIP: https://github.com/kestra-io/kestra/pull/2007#issuecomment-1701613722 

## Logs

In the same way as **expanding** the **tasks** in the topology view, several users would LOVE to **expand the logs** of subflows directly from the parent flow's Execution. To accomplish that, the logs page in the UI will have to display the task runs of the subflow's Execution.

Figma design: https://github.com/kestra-io/kestra/issues/1701#issuecomment-1706321590

```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/774
- [ ] https://github.com/kestra-io/kestra/issues/1701
- [ ] https://github.com/kestra-io/kestra/issues/1815
- [ ] https://github.com/kestra-io/kestra/issues/2114
```
