### ISSUE TITLE
📊 Dashboards, metrics & saved searches

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2050]
Based on user requests, we want to support custom dashboards for easier **operations** and **analytics**. 

## User stories and use cases

1. #1985 “I'd like to `export` the Executions data to build a custom analytical dashboard around which flows succeed/fail” 
2. #1286 “I’d like to see at a glance all `metrics` related to my flow or namespace, including both `Executions` and `Task Runs` ”
3. #140 “I’d like to see at a glance all metrics that Kestra makes available via `Prometheus` collectors in order to create a custom `Grafana` dashboard. Ideally, Kestra provides such a dashboard out of the box.”

## Main objectives

Make it easy to export and analyze executions, metrics, and infra-level metrics in Kibana, Grafana, etc.

```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/1286
- [ ] https://github.com/kestra-io/kestra/issues/1985
- [ ] https://github.com/kestra-io/docs/issues/140
- [ ] https://github.com/kestra-io/kestra/issues/1447
- [ ] https://github.com/kestra-io/kestra-ee/issues/15
- [ ] https://github.com/kestra-io/kestra-ee/issues/13
- [ ] https://github.com/kestra-io/kestra/issues/1563
```

**Comment by anna-geller** [comment]
closing as only one issue left
