### ISSUE TITLE
📈 Add more ways of filtering Executions and Task Runs tables (new columns, saved searches)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2080]
## User stories and use cases

1. #1397 The operations team needs to keep track of specific Executions (and related Task Runs) and doesn’t want to manually filter the Executions list over and over again. Saving the query as a sort of “Saved search” would be desirable to satisfy the following use cases:
    - List Executions in the `Failed/Warning` state in the past `1 hour` filtered by a `Label` (e.g.`env:pre-production`) and namespace
    - List Executions in `any state` filtered by a `Label` (e.g.`env:pre-production`)
    - List Executions in the `Paused` state in the `past 24 h` for a specific flow
2. #566 Users want to `select` which `columns` should be displayed in the `Executions` list — the UI should add additional columns, including `inputs`, `variables`, `revision`, `taskId` (currently executed task or the one from the last task run), as well as the `previous/next` Execution dates for a scheduled trigger.

## Main objectives

Improve the UX for `Executions` filtering by:
  - extending the number of columns available in the data table on the Executions page
  - allowing users to customize which ones are shown 
  - and allowing them to save such prefiltered result sets as custom Dashboards (aka saved search)

```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/1397
- [ ] https://github.com/kestra-io/kestra/issues/566
- [ ] https://github.com/kestra-io/kestra-ee/issues/407
```
