### ISSUE TITLE
🙍‍♂️ Human-in-the-loop enhancements — Part 1

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2104]
## Current state

For now, we support:
- Pause and Resume functionality: e.g. after user approval, flow execution can resume.
- Flow trigger allows to execute tasks as soon as Execution(s) of a given flow(s) move(s) into the Paused state

## TODO

We plan to extend support for the human in the loop with a dedicated UI page allowing users to conveniently manage human tasks while still retaining the definition of such process in code. The scope will likely include:
- adding tasks that will run as soon as a flow moves into a Paused state e.g. to send a **notification** to the human about action that needs to be taken
- adding **reminder** tasks that will fire after the time for approval has elapsed 
- adding support for custom **forms** that can be:
  - sent in notification tasks to humans for approval/resuming the workflow
  - displayed in the UI to approve/resume the process from the UI

```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/1581
- [ ] https://github.com/kestra-io/kestra/issues/1041
- [ ] https://github.com/kestra-io/kestra/issues/3601
```

**Comment by phdbrianlee** [comment]
Hi, Anna Geller, this is a great news. I can add more use cases here.  Assuming there is a workflow requires three tasks to be completed one-by-one.  The first and third tasks are automated processes.  While the second task is a manual task that needs to be divided into 10 sub-tasks, which multiple users are responsible for manually completing each sub-task.   This may require the form to have a task list function which can be modified by the user.
