### ISSUE TITLE
[UI] Follow up to top navigation bar changes - Search bar

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2322]
In 0.13.0, we are introducing a global search bar, which doesn't allow arrow navigation yet.

```[tasklist]
### Tasks
- [x] Allow searching for flows
- [x] Allow searching for a specific Execution by ID
- [x] Allow searching for namespaces (EE)
```

**Comment by MilosPaunovic** [comment]
Would say we could close this one, as the Search bar changed significantly from when this was opened @anna-geller?
