### ISSUE TITLE
VS Code Editor Follow-up

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2337]
```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/2381
- [ ] https://github.com/kestra-io/kestra/issues/2367
- [ ] https://github.com/kestra-io/kestra/issues/2342
- [ ] https://github.com/kestra-io/kestra/issues/2374
- [ ] https://github.com/kestra-io/kestra/issues/2405
- [ ] https://github.com/kestra-io/kestra/issues/2341
- [ ] https://github.com/kestra-io/kestra/issues/2340
- [ ] https://github.com/kestra-io/kestra/issues/2368
- [ ] https://github.com/kestra-io/kestra/issues/2594
- [ ] https://github.com/kestra-io/kestra/issues/2345
- [ ] https://github.com/kestra-io/kestra/issues/2355
- [ ] https://github.com/kestra-io/kestra/issues/2366
- [ ] https://github.com/kestra-io/kestra/issues/2335
- [ ] https://github.com/kestra-io/terraform-provider-kestra/issues/91
- [ ] https://github.com/kestra-io/kestra/issues/2369
- [ ] https://github.com/kestra-io/kestra/issues/2343
- [ ] https://github.com/kestra-io/kestra/issues/2336
- [ ] https://github.com/kestra-io/kestra/issues/2338
- [ ] https://github.com/kestra-io/kestra/issues/2339
```
