### ISSUE TITLE
Retry epic

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2567]
### Feature description

```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/2550
- [ ] https://github.com/kestra-io/kestra/issues/1496
- [ ] Move retry functionality from Worker to Executor
```

**Comment by Skraye** [comment]
close by https://github.com/kestra-io/kestra/commit/81f281e92b7fafb32dc9dbd11fff179378aff835
