### ISSUE TITLE
[Epic] Allow manually changing the Execution state

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4447]
### Feature description

![image](https://github.com/user-attachments/assets/3eae1c2e-141f-4943-a7b2-36731af6c99e)

This should allow to manually set e.g. a `Failed` execution to success e.g., after a manual fix.

**Important**: this change MUST generate an audit log (who made that change, when, and optionally why). It would be great if the user could provide a comment for why the execution state was changed - not sure how this would need to be stored, within an audit log or as a label?

- [ ] allow the transition in our state machine (concurrency limits should be unaffected by this)
- [ ] one-liner change in terms of backend impact to enable the feature
- [ ] front-end addition

## Related issues
- https://github.com/kestra-io/kestra/issues/4260
- https://github.com/kestra-io/kestra/issues/2423
