### ISSUE TITLE
[Epic] Improve the functionality of the low-code UI forms (accessed from the topology view)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4581]
### Feature description

We see multiple issues related to the fact that the low-code UI forms have been neglected for a while. 

Some properties cannot be adjusted from low-code forms, others don't correctly save a new Flow revision.

This epic is to consolidate all issues related to low-code forms and tackle them in one bigger project:

- [x] https://github.com/kestra-io/kestra/issues/4564
- [x] https://github.com/kestra-io/kestra-ee/issues/1477 
- [x] https://github.com/kestra-io/kestra/issues/3811
- [x] https://github.com/kestra-io/kestra/issues/4570
- [x] https://github.com/kestra-io/kestra/issues/1090
- [x] https://github.com/kestra-io/kestra/issues/4762
- [x] https://github.com/kestra-io/kestra/issues/4882
- [x] https://github.com/kestra-io/kestra/issues/4568
