### ISSUE TITLE
[Epic] Inputs Enhancements

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4656]
### Feature description

As part of 0.19.0, we want to significantly improve inputs to offer a  🫶 _delightful_ 🫶 UX upon which we can build upcoming UI forms in the future — issues listed in the priority order:
- [x] https://github.com/kestra-io/kestra/issues/3610
- [x] https://github.com/kestra-io/kestra/issues/4470 
- [x] https://github.com/kestra-io/kestra/issues/3742
- [x] https://github.com/kestra-io/kestra/issues/3710 
- [x] https://github.com/kestra-io/kestra/issues/3697
- [x] https://github.com/kestra-io/kestra/issues/4661
- [x] https://github.com/kestra-io/kestra/issues/4340
- [x] https://github.com/kestra-io/kestra/issues/4062
- [x] https://github.com/kestra-io/kestra/issues/4126
- [x] https://github.com/kestra-io/kestra/issues/4496

**Comment by anna-geller** [comment]
🎉
