### ISSUE TITLE
[Epic] Improve error handling

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4701]
## Context
Current error handling with errors on Flowable + Flow trigger works for simple use cases but has some limitations:
- not possible to capture the stack traces or IDs of tasks that failed
- not possible to react to a specific kind of failure (e.g. if `task_a` fails, launch `subflow_b` but allow failure of `task_a` so that Execution is not considered failed as its failure is handled by `subflow_b`)

## To dos
- [x] https://github.com/kestra-io/kestra/issues/172
- [x] https://github.com/kestra-io/kestra/issues/2116 
- [x] https://github.com/kestra-io/kestra/issues/2000
- [x] https://github.com/kestra-io/kestra/issues/4394 
- [x] https://github.com/kestra-io/kestra-ee/issues/560
- [x] https://github.com/kestra-io/kestra/issues/2840

**Comment by anna-geller** [comment]
most of that handled in 0.22, 1 issue left and will be tracked there
