### ISSUE TITLE
[Epic] Handle issues that can make the application crash

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4702]
### Feature description

- [x] https://github.com/kestra-io/kestra/issues/1434
- [x] https://github.com/kestra-io/kestra-ee/issues/3083
- [ ] https://github.com/kestra-io/kestra-ee/issues/501 -- there is an issue in Kafka where an execution can't find the flow, then it crashes the executor because of async processing
- [x] https://github.com/kestra-io/kestra-ee/issues/1337
- [x] https://github.com/kestra-io/kestra/issues/4631
- [x] https://github.com/kestra-io/kestra/issues/2188
