### ISSUE TITLE
[Epic] Improve plugin docs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4707]
### Feature description

- [x] display names https://github.com/kestra-io/docs/issues/1456 
- [x] Move Plugin documentation to JSON-schema-based doc https://github.com/kestra-io/kestra/issues/3731 
- [x] new docs display - Nico's design https://github.com/kestra-io/kestra/issues/4154 
- [x] partially related https://github.com/kestra-io/kestra-ee/issues/1535

**Comment by brian-mulier-p** [comment]
Still to be done: adapt website component to use the new UI-LIBS layout and add some styling

**Comment by brian-mulier-p** [comment]
Closing in favor of kestra-io/docs#2140 as it's only a website work now
