### ISSUE TITLE
Hide deprecated features by default

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#4905]
## Next Steps

We will:
- [x] not show deprecated plugins in the Editor's autocompletion (will be complex)
- [x] we will also filter them out in the Topology view
- [x] for both Editor and low-code Topology forms, we need to hide deprecated properties like `runner` for script tasks 
- [x] for the /ui/plugins, https://github.com/kestra-io/kestra/issues/4526#issuecomment-2352517512
- [x] for the website also see issue above -- users can still find documentation for deprecated plugins from the built-in documentation in the Editor in the UI 
- [x] for Blueprints, we soon will have versioned blueprints to ensure deprecated functionality is not shown

### Feature description

In views like Topology and Plugins, we show deprecated features. It can be unclear to end users whether functionality is still supported when they use them in this way. 

Instead, we should hide these plugins by default, e.g. take topology for example, the first 3 items are deprecated 
![image](https://github.com/user-attachments/assets/2489b528-5236-4f86-ae02-bcb14f035e98)

Instead of showing these, we should hide them. However, users should still be able to find them if needed -- possible options to consider:
- a configuration explicitly enabling deprecated plugins
- a UI toggle which will display the deprecated plugins
```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/7205
- [ ] https://github.com/kestra-io/kestra/issues/7206
```

**Comment by MilosPaunovic** [comment]
I believe this need to be handled on the BE side.

**Comment by MilosPaunovic** [comment]
Related https://github.com/kestra-io/kestra/issues/4526
