### ISSUE TITLE
Add Favorites/Starred UI menu to bookmark UI pages

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5660]
As the UI pages keep growing, we should have a way to add some UI pages to favorites (`Starred`) and access them quickly. [Figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3256-39461&t=1CxPaw8udxQznQqF-4)

![image](https://github.com/user-attachments/assets/9d87f724-ce7a-4e28-aa2a-8fa3291130ed)

Technically, we should store the favorites/starred inside the User object in the DB so that users can access their favorites across browser sessions.
```[tasklist]
### Tasks
- [x] add star to the title bar
- [x] store star system in localStorage
- [x] handle expanded sidebar
- [x] handle collapsed sidebar
```

**Comment by anna-geller** [comment]
Add a JSON configuration with a dump of user preferences and Starred pages stored in a dedicated property within a User object, including:

1. Settings
2. Starred
3. Saved searched

Alternative: User Java object 

We can start with a frontend implementation storing everything locally and then add the backend to store it on the User object

**Comment by elevatebart** [comment]
Do we have a design for when the SideBar is collapsed or should I suggest one?

Additional design assumptions: 
- When the **current page** is favorited, the star should be full instead of only outline. Optionally, the page in the list should be in a lighter color so we can find it easily.
- New pages should be ordered by **alphabetical** order by default
- We should limit this list by default to **5 pages**. this will avoid user asking too quickly for directories and renames
- The pages are taking the "title" seen in the `TopNavBar.vue`. It is longer and will prevent collision.

Further implementation ideas we could add later:
- Re-order the list
- Use Icon of current page
- Change title

**Comment by Nico-Kestra** [comment]
Yep for current page is favorited we have this: 
<img width="1051" alt="Favorites" src="https://github.com/user-attachments/assets/cf5280aa-c2da-4e90-b62d-c1dfff2cd43a">
[Figma](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=3869-37658&t=UQiavs8ahh64WlYt-1)

For when the sidebar is collapsed we have this for Administration:
<img width="318" alt="Capture d’écran 2024-10-30 à 17 11 26" src="https://github.com/user-attachments/assets/f994b118-bec7-4047-81ab-5564b6dba488">
It could really use a design review, as it doesn’t look very appealing.

**Comment by anna-geller** [comment]
> We should limit this list by default to 5 pages.  

This seems a little arbitrary, let's not impose any limits, it's up to the user to choose how many bookmarks they need 👍 I asked Nico to explore additional ways of how we can handle a large number of those
