### ISSUE TITLE
Improvements of new filter functionality

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5845]
Right now, there are new filters only on `Executions` page. It's not yet  fully completed, but it's being [merged](https://github.com/kestra-io/kestra/pull/5844) so I can get more feedback from the rest of the team.

Below is the list of known issues and tasks to be implemented, anything else you find or notice, feel free to add as comment below and it will be amended.

- [x] Implement search triggering on adding new filter value (full adding), as now it is confusing why the content is not filtered  when we chose filters (we can remove the search button itself, maybe involves a bit of work around the `recent` functionality).
- [x] Handle `recent` functionality better due to filters being triggered automatically now. 
- [x] Allow selection of values in dropdown on Enter key press.
- [x] Add complete keyboard navigation as part of dropdowns.
- [x]  Submit filter query on Enter key press.
- [x]  #5924
- [x]  #5984
- [x]  Add button to handle the table options (selection of visible columns), this should be an option on the table itself.
- [x]  If there already is property with same label and comparator, add value to it instead creation of new tag. [#6028](https://github.com/kestra-io/kestra/issues/6028)
- [x] If property is marked as `multiple`, only then allow multiple values, if not, replace existing value with new one.
- [x] #5925
- [x] #5955
- [x] #5954
- [x] #5926
- [x] #5927
- [x] #5928
- [x] #5929
- [x] #5931
- [x] #5912
- [x] #5911
- [x]  Add button to handle the page settings (show charts). [#5905](https://github.com/kestra-io/kestra/pull/5905)
- [x]  Add remaining filter options for Executions context (Relative date, Absolute date). [#5898](https://github.com/kestra-io/kestra/pull/5898)

Related issue https://github.com/kestra-io/kestra/issues/4664.

**Comment by elevatebart** [comment]
## notes from Demo

The options popper at the end of the filter bar looks like a tooltip. Could we make the content a little lighter in dark mode? (might be element plus)
Placeholder color looks exactly like paragraph text. Is it normal? It does not feel normal. 
Could we have the comparator ("is") be in a different color to improve readability (specially since text is incredibly small)
Date filters ideas
- inspire from gmail search (great readability)
- dates should be humanly readable instead of std date format [(use Intl)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)

**Comment by MilosPaunovic** [comment]
Updated the issue description with Bart's notes from the comment above, and, with notes from the rest of the team collected during the demo.

**Comment by brian-mulier-p** [comment]
More of a QOL thing but would be great if clicking on an existing filter would allow changing the values for it (I know it has some challenges like what to change because we don't have multiple boxes to separate comparator, key and value), maybe allow changing the value upon clicking for now ?

**Comment by anna-geller** [comment]
@MilosPaunovic can we split this in to what's critical and must be done before release on Tuesday and the rest we can do later? 🙏

**Comment by MilosPaunovic** [comment]
Nothing remaining seems critical.
