### ISSUE TITLE
0.20 launch, UI display weird behaviours list

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#6290]
### Describe the issue

Here's a quick listing of the weird UI behaviour i came across in the newly launched 0.20 of Kestra, some points may be more of a "request and feedback" type, apologies. 
---
---
![image](https://github.com/user-attachments/assets/e088fb7f-06ef-4952-9ca3-dc5ebbb1e4cd)
![image](https://github.com/user-attachments/assets/299a5024-0c59-414e-9d6c-f483a4421f2f)
```[tasklist]
### Tasks
- [x] As you can see with the two pictures above, the date filtering doesn't follow the date format specified in the settings. (Done in https://github.com/kestra-io/kestra/pull/6335)
```
---
---
![image](https://github.com/user-attachments/assets/b61ab5f6-465d-48c1-b50e-b5121da9ea15)
```[tasklist]
### Tasks
- [x] As you can see with the above picture, some of the total executions legends (related to the gauge display) are out of bounding. (done in https://github.com/kestra-io/kestra/pull/5971)
```
---
---
![image](https://github.com/user-attachments/assets/c4a60159-1978-4fe4-84b2-d964b899cf55)
![image](https://github.com/user-attachments/assets/48f1f10b-8091-4745-a127-5ed62f162887)
```[tasklist]
### Tasks
- [ ] ~~As you can see with the above two pictures, hovering the filter box trigger the scrollbar which hide the majority of the filter himself, interacting with the filter is a lot more complicated.~~ Moved to a separate issue : https://github.com/kestra-io/kestra/issues/6338
``` 
---
---
![image](https://github.com/user-attachments/assets/6186a47f-8583-4012-af79-e08f0d080bda)
```[tasklist]
### Tasks
- [ ] ~~As you can see with the above picture, green blocks, the field "next execution date" display a date for realTime triggers, which is weird, and what's more, it display instead the "creation date" i guess.~~ Moved to a separate issue : https://github.com/kestra-io/kestra/issues/6340
- [x] As you can see with the above picture, red block, IDs of triggers are truncated, in my opinion this info is of upmost importance since it permits to understand easily the diff between triggers of the same flow. (Done in https://github.com/kestra-io/kestra/pull/6336)
```

### Environment

- Kestra Version: 0.20.0 OSS docker compose debian

**Comment by Muppasanipraneeth** [comment]
@MilosPaunovic  can you assign it to me

**Comment by MilosPaunovic** [comment]
Yup, go ahead! 🚀

**Comment by Muppasanipraneeth** [comment]
sorry @MilosPaunovic  sir I though it is reactjs but it is vuejs I am not familiar with it

**Comment by ReLoutre** [comment]
![Animation](https://github.com/user-attachments/assets/ae23e6a1-b618-42b0-8797-b3f9a27edadc)
Found out that expanding then collapsing some of the right side menus fix the display of the executions legends.

**Comment by sanjaykumar584** [comment]
@MilosPaunovic I would like to work on this issue. Can you assign it to me?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @sanjaykumar584! 🚀

**Comment by MilosPaunovic** [comment]
Hey @ReLoutre,

First two issues from the list are amended and merged to `develop`.

I need more details about the third one:

> As you can see with the above two pictures, hovering the filter box trigger the scrollbar which hide the majority of the filter himself, interacting with the filter is a lot more complicated.

I cannot reproduce it on Google Chrome, on Linux. Can you specify more details about browser/OS used?

Also, for the future, if you could open separate issues per problem, it would make things a lot simpler from tracking purposes.

**Comment by MilosPaunovic** [comment]
Only two things remain here:

1. Scroll issue (@ReLoutre if you could open separate issue with more details, that would be great)

2. > As you can see with the above picture, green blocks, the field "next execution date" display a date for realTime triggers, which is weird, and what's more, it display instead the "creation date" i guess.

@Ben8t could give us more info about the second point, and will open a separate issue, if necessary. 

@sanjaykumar584 We had to amend those issues quickly, so I took over. If you're still up for contributing, may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

I am closing this issue now.

**Comment by Ben8t** [comment]
> As you can see with the above picture, green blocks, the field "next execution date" display a date for realTime triggers, which is weird, and what's more, it display instead the "creation date" i guess.

RealTimeTriggers have `waitTime` and `conditions` properties so it make sense in some cases to have "next date". I believe it's best to see this "next execution date" as the next "evaluation" of the trigger in case of RealTimeTrigger.

Still I agree, "create date" and "next execution date" should be different. Can you open a dedicated issue for this @ReLoutre please ?

**Comment by ReLoutre** [comment]
Hi @MilosPaunovic ,
Sry for the listing thing, thought it was a good idea (fail happens).

Regarding the third point :
- I'm mainly using Firefox
- I'm accessing the web page through a windows 10 os
- Problem is that interacting with crosses of the filter are a bit tricky (while it's still possible) since the hovering box of the scroll bar seems to reach the center of the filter box
![image](https://github.com/user-attachments/assets/67da3428-60d0-4472-80d3-4001d936a354)
![image](https://github.com/user-attachments/assets/216e6b2c-42a0-4f96-961d-e2e82f04bec2)
- New info, seems like zooming out (even by 10%, so having a zoom of 90% instead of 100%) make the scroll bar completely disappear. And while zooming in up to 200% the scroll bar disappear as well. On some pages in does not appear and some other it does. And most of the time, it appears while not being useful at all (since the filter is already completely visible, while in some case it could be useful but it doesn't appear). The behaviour of this scroll bar is highly inconsistent.    Having it under the box could be good.

Useful but do not appear :
![image](https://github.com/user-attachments/assets/eff5e390-6c6d-4992-8d59-f1ca0e0b18f1)
Useless but appear :
![image](https://github.com/user-attachments/assets/507e2363-ebb0-4dfa-ab66-2bed4407176f)

**Comment by ReLoutre** [comment]
> > As you can see with the above picture, green blocks, the field "next execution date" display a date for realTime triggers, which is weird, and what's more, it display instead the "creation date" i guess.
> 
> RealTimeTriggers have `waitTime` and `conditions` properties so it make sense in some cases to have "next date". I believe it's best to see this "next execution date" as the next "evaluation" of the trigger in case of RealTimeTrigger.
> 
> Still I agree, "create date" and "next execution date" should be different. Can you open a dedicated issue for this @ReLoutre please ?

I'm on it @Ben8t !

**Comment by ReLoutre** [comment]
> Scroll issue (@ReLoutre if you could open separate issue with more details, that would be great)

Forgot to make it separate, i'll do another issue too.

**Comment by ReLoutre** [comment]
Here's the two new issues :
https://github.com/kestra-io/kestra/issues/6338
https://github.com/kestra-io/kestra/issues/6340
