### ISSUE TITLE
Schedule a flow at specific date(s), or exclude certain date(s) from schedule trigger conditions

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#877]
A new use case will be to be able to schedule a flow at a specific date(s). 
For example, I don't want to schedule it with a cron tab expression but be able to manually add date of triggering: 

- It will required a new Trigger : 
```yaml 
triggers:
  - id: manual
    type: io.kestra.core.models.triggers.types.Manual
```
- On the ui side, add way to input a DateTime picker (and maybe inputs)
- You can queue as many execution as you want  
- The scheduler will look at the specific date and remove them from the storage when a create a new execution
```[tasklist]
### Tasks
- [ ] Add specific dates to any schedule trigger
- [ ] Exclude specific dates from a schedule trigger
- [ ] Include or exclude holidays from schedule trigger conditions
```

**Comment by loicmathieu** [comment]
You can see it in multiple ways:
- Creating a "FixedDateSchedule" with a list of date in the YAML
- Creating a "ManualScehedule" that can only be triggered manually from the CLI/API/UI

I wonder if queuing triggers is a good idead, we will need a way to saw those queued triggers and manage them so it will be a lot of efforts.

**Comment by tchiotludo** [comment]
same than this : https://github.com/kestra-io/kestra/issues/1762

**Comment by anna-geller** [comment]
solution until dedicated date picker is added:

```yaml
id: schedule
namespace: dev

tasks:
  - id: API
    type: "io.kestra.plugin.fs.http.Request"
    uri: "https://jsonplaceholder.typicode.com/posts/1"
    method: GET

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    timezone: Europe/Berlin
    cron: "3 14 6 12 *" # "minute hour day month *"
```

**Comment by anna-geller** [comment]
superseded by https://github.com/kestra-io/kestra/issues/3818
